/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bryandatabase;

import javax.swing.JOptionPane;

/**
 *
 * @author CL2-PC
 */
public class MidtermACT_RPS extends javax.swing.JFrame {

    /**
     * Creates new form MidtermACT_RPS
     */
    public MidtermACT_RPS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Player1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel2.setText("Player2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 190, 30));
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 190, 30));

        jButton1.setText("VS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jLabel3.setText("ROCK");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel4.setText("PAPER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        jLabel5.setText("SCISSOR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String p1 = txt1.getText().trim().toUpperCase();
       String p2 = txt2.getText().trim().toUpperCase();

if (p1.equals("ROCK") && p2.equals("ROCK")) {
    JOptionPane.showMessageDialog(rootPane, "DRAW", "RPS", JOptionPane.INFORMATION_MESSAGE);
} 
else if (p1.equals("ROCK") && p2.equals("PAPER")) {
    JOptionPane.showMessageDialog(rootPane, "PLAYER 2 WIN", "RPS", JOptionPane.INFORMATION_MESSAGE);
} 
else if (p1.equals("ROCK") && p2.equals("SCISSOR")) {
    JOptionPane.showMessageDialog(rootPane, "PLAYER 1 WIN", "RPS", JOptionPane.INFORMATION_MESSAGE);
} 
else if (p1.equals("PAPER") && p2.equals("ROCK")) {
    JOptionPane.showMessageDialog(rootPane, "PLAYER 1 WIN", "RPS", JOptionPane.INFORMATION_MESSAGE);
} 
else if (p1.equals("PAPER") && p2.equals("PAPER")) {
    JOptionPane.showMessageDialog(rootPane, "DRAW", "RPS", JOptionPane.INFORMATION_MESSAGE);
} 
else if (p1.equals("PAPER") && p2.equals("SCISSOR")) {
    JOptionPane.showMessageDialog(rootPane, "PLAYER 2 WIN", "RPS", JOptionPane.INFORMATION_MESSAGE);
} 
else if (p1.equals("SCISSOR") && p2.equals("ROCK")) {
    JOptionPane.showMessageDialog(rootPane, "PLAYER 2 WIN", "RPS", JOptionPane.INFORMATION_MESSAGE);
} 
else if (p1.equals("SCISSOR") && p2.equals("PAPER")) {
    JOptionPane.showMessageDialog(rootPane, "PLAYER 1 WIN", "RPS", JOptionPane.INFORMATION_MESSAGE);
} 
else if (p1.equals("SCISSOR") && p2.equals("SCISSOR")) {
    JOptionPane.showMessageDialog(rootPane, "DRAW", "RPS", JOptionPane.INFORMATION_MESSAGE);
} 
else {
    JOptionPane.showMessageDialog(rootPane, "Invalid Input", "RPS", JOptionPane.ERROR_MESSAGE);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MidtermACT_RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MidtermACT_RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MidtermACT_RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MidtermACT_RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MidtermACT_RPS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
